In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
df=pd.read_csv('Advertising.csv')

In [4]:
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
df=df.drop('Unnamed: 0',axis=1)

In [13]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [15]:
df.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [17]:
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from tensorflow.keras.layers import Dense

In [18]:
x=df.drop('Sales',axis=1)
y=df['Sales']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=101)

In [19]:
model=Sequential()

In [20]:
model.add(Dense(32,activation='relu',input_dim=len(x_train.columns)))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='linear'))
model.compile(optimizer='adam',loss='mean_squared_error')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 32)                128

 dense_1 (Dense)             (None, 64)                2112

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 4,353
Trainable params: 4,353
Non-trainable params: 0
_________________________________________________________________

In [27]:
history=model.fit(x_train,y_train,validation_split=0.1,epochs=97)

Epoch 1/97
6/6 [==============================] - 0s 23ms/step - loss: 0.2567 - val_loss: 0.1468
Epoch 2/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2523 - val_loss: 0.1539
Epoch 3/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2549 - val_loss: 0.1685
Epoch 4/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2356 - val_loss: 0.1970
Epoch 5/97
6/6 [==============================] - 0s 14ms/step - loss: 0.3656 - val_loss: 0.1867
Epoch 6/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2526 - val_loss: 0.1527
Epoch 7/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2659 - val_loss: 0.2202
Epoch 8/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2704 - val_loss: 0.2497
Epoch 9/97
6/6 [==============================] - 0s 11ms/step - loss: 0.3481 - val_loss: 0.1543
Epoch 10/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3756 - val_loss: 0.4482
Epoch 11/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3790 - val_loss: 0.2551
Epoch 12/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3733 - val_loss: 0.3482
Epoch 13/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3082 - val_loss: 0.1750
Epoch 14/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3313 - val_loss: 0.1623
Epoch 15/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2955 - val_loss: 0.1328
Epoch 16/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2655 - val_loss: 0.4470
Epoch 17/97
6/6 [==============================] - 0s 13ms/step - loss: 0.5377 - val_loss: 0.1684
Epoch 18/97
6/6 [==============================] - 0s 10ms/step - loss: 0.5009 - val_loss: 0.4831
Epoch 19/97
6/6 [==============================] - 0s 10ms/step - loss: 0.6730 - val_loss: 1.3888
Epoch 20/97
6/6 [==============================] - 0s 11ms/step - loss: 0.8910 - val_loss: 0.2374
Epoch 21/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3956 - val_loss: 0.1796
Epoch 22/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2768 - val_loss: 0.2516
Epoch 23/97
6/6 [==============================] - 0s 10ms/step - loss: 0.2840 - val_loss: 0.1934
Epoch 24/97
6/6 [==============================] - 0s 10ms/step - loss: 0.2805 - val_loss: 0.3976
Epoch 25/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3345 - val_loss: 0.1407
Epoch 26/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2704 - val_loss: 0.1586
Epoch 27/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3033 - val_loss: 0.1773
Epoch 28/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2840 - val_loss: 0.1599
Epoch 29/97
6/6 [==============================] - 0s 17ms/step - loss: 0.2404 - val_loss: 0.2161
Epoch 30/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3033 - val_loss: 0.1356
Epoch 31/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2625 - val_loss: 0.1462
Epoch 32/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2522 - val_loss: 0.2940
Epoch 33/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3628 - val_loss: 0.1642
Epoch 34/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2574 - val_loss: 0.1386
Epoch 35/97
6/6 [==============================] - 0s 16ms/step - loss: 0.2320 - val_loss: 0.5324
Epoch 36/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3294 - val_loss: 0.2020
Epoch 37/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3004 - val_loss: 0.2763
Epoch 38/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3656 - val_loss: 0.3558
Epoch 39/97
6/6 [==============================] - 0s 10ms/step - loss: 0.2882 - val_loss: 0.2359
Epoch 40/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3438 - val_loss: 0.1886
Epoch 41/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3500 - val_loss: 0.2442
Epoch 42/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2853 - val_loss: 0.1764
Epoch 43/97
6/6 [==============================] - 0s 10ms/step - loss: 0.2503 - val_loss: 0.1221
Epoch 44/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3123 - val_loss: 0.3940
Epoch 45/97
6/6 [==============================] - 0s 10ms/step - loss: 0.4085 - val_loss: 0.1285
Epoch 46/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2835 - val_loss: 0.1714
Epoch 47/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3043 - val_loss: 0.5618
Epoch 48/97
6/6 [==============================] - 0s 13ms/step - loss: 0.3220 - val_loss: 0.2243
Epoch 49/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2742 - val_loss: 0.2542
Epoch 50/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2493 - val_loss: 0.1435
Epoch 51/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2441 - val_loss: 0.3260
Epoch 52/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2837 - val_loss: 0.2237
Epoch 53/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2871 - val_loss: 0.4821
Epoch 54/97
6/6 [==============================] - 0s 11ms/step - loss: 0.6580 - val_loss: 0.4819
Epoch 55/97
6/6 [==============================] - 0s 13ms/step - loss: 0.4217 - val_loss: 0.1752
Epoch 56/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2683 - val_loss: 0.1940
Epoch 57/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2539 - val_loss: 0.1891
Epoch 58/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2744 - val_loss: 0.3068
Epoch 59/97
6/6 [==============================] - 0s 12ms/step - loss: 0.5818 - val_loss: 0.8703
Epoch 60/97
6/6 [==============================] - 0s 12ms/step - loss: 0.8786 - val_loss: 0.4901
Epoch 61/97
6/6 [==============================] - 0s 12ms/step - loss: 0.4468 - val_loss: 0.5123
Epoch 62/97
6/6 [==============================] - 0s 12ms/step - loss: 0.6015 - val_loss: 0.4964
Epoch 63/97
6/6 [==============================] - 0s 12ms/step - loss: 0.4898 - val_loss: 0.1919
Epoch 64/97
6/6 [==============================] - 0s 10ms/step - loss: 0.3068 - val_loss: 0.1530
Epoch 65/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2662 - val_loss: 0.2455
Epoch 66/97
6/6 [==============================] - 0s 8ms/step - loss: 0.2488 - val_loss: 0.1580
Epoch 67/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2534 - val_loss: 0.2976
Epoch 68/97
6/6 [==============================] - 0s 11ms/step - loss: 0.6356 - val_loss: 0.5894
Epoch 69/97
6/6 [==============================] - 0s 12ms/step - loss: 0.4759 - val_loss: 0.2193
Epoch 70/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3040 - val_loss: 0.4017
Epoch 71/97
6/6 [==============================] - 0s 13ms/step - loss: 0.7937 - val_loss: 1.3708
Epoch 72/97
6/6 [==============================] - 0s 12ms/step - loss: 0.9126 - val_loss: 0.7298
Epoch 73/97
6/6 [==============================] - 0s 12ms/step - loss: 0.6967 - val_loss: 0.2972
Epoch 74/97
6/6 [==============================] - 0s 11ms/step - loss: 0.4576 - val_loss: 0.1751
Epoch 75/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3920 - val_loss: 0.2023
Epoch 76/97
6/6 [==============================] - 0s 11ms/step - loss: 0.3198 - val_loss: 0.2366
Epoch 77/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3335 - val_loss: 0.2283
Epoch 78/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2550 - val_loss: 0.1445
Epoch 79/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2419 - val_loss: 0.1279
Epoch 80/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2509 - val_loss: 0.1845
Epoch 81/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2434 - val_loss: 0.1895
Epoch 82/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2718 - val_loss: 0.4122
Epoch 83/97
6/6 [==============================] - 0s 12ms/step - loss: 0.3034 - val_loss: 0.1953
Epoch 84/97

6/6 [==============================] - 0s 11ms/step - loss: 0.3018 - val_loss: 0.2061
Epoch 85/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2438 - val_loss: 0.2422
Epoch 86/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2888 - val_loss: 0.1858
Epoch 87/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2317 - val_loss: 0.2484
Epoch 88/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2556 - val_loss: 0.2029
Epoch 89/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2735 - val_loss: 0.3850
Epoch 90/97
6/6 [==============================] - 0s 11ms/step - loss: 0.3151 - val_loss: 0.2159
Epoch 91/97
6/6 [==============================] - 0s 11ms/step - loss: 0.2309 - val_loss: 0.1946
Epoch 92/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2320 - val_loss: 0.1587
Epoch 93/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2278 - val_loss: 0.2434
Epoch 94/97
6/6 [==============================] - 0s 11ms/step - loss: 0.3653 - val_loss: 0.2605
Epoch 95/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2412 - val_loss: 0.2296
Epoch 96/97
6/6 [==============================] - 0s 13ms/step - loss: 0.2768 - val_loss: 0.1987
Epoch 97/97
6/6 [==============================] - 0s 12ms/step - loss: 0.2239 - val_loss: 0.2149

In [30]:
pre=model.predict(x_test)

1/1 [==============================] - 0s 298ms/step

In [32]:
print(pre[0:5])
print(y_test[0:5])

[[14.567043]
 [19.55524 ]
 [12.662927]
 [17.279404]
 [ 8.508662]]
37     14.7
109    19.8
31     11.9
89     16.7
66      9.5
Name: Sales, dtype: float64

In [37]:
model.predict(np.array([25,30,35]).reshape(1,3))

1/1 [==============================] - 0s 315ms/step

array([[8.234521]], dtype=float32)